CREATE TABLE TB_PAPEL_USUARIO_API(
	ID_PAPEL_USUARIO_API SERIAL PRIMARY KEY,
	STR_NOME VARCHAR(50) NOT NULL,
	BOL_ATIVO BIT NOT NULL
);

CREATE TABLE TB_USUARIO_API(
	ID_USUARIO_API SERIAL PRIMARY KEY,
	STR_USUARIO VARCHAR(50) NOT NULL,
	STR_SENHA VARCHAR(500) NOT NULL,
	ID_PAPEL_USUARIO_API INTEGER NOT NULL,
    CONSTRAINT FK1_PAPEL_USUARIO_API
        FOREIGN KEY(ID_PAPEL_USUARIO_API) 
        REFERENCES TB_PAPEL_USUARIO_API(ID_PAPEL_USUARIO_API),
	BOL_ATIVO BIT NOT NULL
);

CREATE TABLE TB_DOMINIO(
	STR_CHAVE VARCHAR(30) NOT NULL,
	STR_DESCRICAO VARCHAR(50) NOT NULL,
	ID_DOMINIO INTEGER NOT NULL,
    PRIMARY KEY (STR_CHAVE, ID_DOMINIO)
);

CREATE TABLE TB_PESSOA(
	ID_PESSOA SERIAL PRIMARY KEY,
	STR_NOME VARCHAR(100) NOT NULL,
	STR_SOBRENOME VARCHAR(100) NOT NULL,
	ID_SEXO INTEGER NOT NULL,
	DT_NASCIMENTO DATE NOT NULL,
	ID_PESSOA_TIPO INTEGER NOT NULL,
	STR_DOCUMENTO VARCHAR(30) NOT NULL,
	ID_TIPO_DOCUMENTO INTEGER NOT NULL
);

CREATE TABLE TB_ESTADO(
	ID_ESTADO SERIAL PRIMARY KEY,
	STR_NOME VARCHAR(30) NOT NULL,
	STR_UF VARCHAR(2) NOT NULL
);

CREATE TABLE TB_CIDADE(
	ID_CIDADE SERIAL PRIMARY KEY,
	STR_NOME VARCHAR(80) NOT NULL,
	ID_ESTADO INTEGER NOT NULL,
	CONSTRAINT FK1_ESTADO
        FOREIGN KEY(ID_ESTADO) 
        REFERENCES TB_ESTADO(ID_ESTADO)
);	
	
CREATE TABLE TB_PESSOA_ENDERECO(
	ID_PESSOA_ENDERECO SERIAL PRIMARY KEY,
	ID_PESSOA INTEGER NOT NULL,
	CONSTRAINT FK1_PESSOA
        FOREIGN KEY(ID_PESSOA) 
        REFERENCES TB_PESSOA(ID_PESSOA),
	ID_CIDADE INTEGER NOT NULL,
	CONSTRAINT FK1_CIDADE
        FOREIGN KEY(ID_CIDADE) 
        REFERENCES TB_CIDADE(ID_CIDADE),
	STR_CEP VARCHAR(8) NOT NULL,
	STR_BAIRRO VARCHAR(50) NOT NULL,
	STR_RUA VARCHAR(50) NOT NULL,
	INT_NUMERO INTEGER NOT NULL,
	STR_COMPLEMENTO VARCHAR(50) NOT NULL
);

CREATE TABLE TB_CATEGORIA_PRODUTO(
	ID_CATEGORIA_PRODUTO SERIAL PRIMARY KEY,
	STR_NOME VARCHAR(30) NOT NULL
);

CREATE TABLE TB_FILIAL(
	ID_FILIAL SERIAL PRIMARY KEY,
	STR_NOME VARCHAR(50) NOT NULL,
	ID_ATIVO BIT NOT NULL,
	ID_CIDADE INTEGER NOT NULL,
	CONSTRAINT FK1_CIDADE
        FOREIGN KEY(ID_CIDADE) 
        REFERENCES TB_CIDADE(ID_CIDADE)	
);

CREATE TABLE TB_PRODUTO(
	ID_PRODUTO SERIAL PRIMARY KEY,
	STR_NOME VARCHAR(30) NOT NULL,
	STR_DESCRICAO VARCHAR(30) NOT NULL,
	ID_CATEGORIA_PRODUTO INTEGER NOT NULL,
	CONSTRAINT FK1_CATEGORIA_PRODUTO
        FOREIGN KEY(ID_CATEGORIA_PRODUTO) 
        REFERENCES TB_CATEGORIA_PRODUTO(ID_CATEGORIA_PRODUTO),
	DEC_VALOR DECIMAL(8, 2) NOT NULL
);

CREATE TABLE TB_PRODUTO_FILIAL(
	ID_PRODUTO INTEGER NOT NULL,
	CONSTRAINT FK1_PRODUTO
        FOREIGN KEY(ID_PRODUTO) 
        REFERENCES TB_PRODUTO(ID_PRODUTO),	
	ID_FILIAL INTEGER NOT NULL,
	CONSTRAINT FK1_FILIAL
        FOREIGN KEY(ID_FILIAL) 
        REFERENCES TB_FILIAL(ID_FILIAL)	
);

CREATE TABLE TB_PEDIDO(
	ID_PEDIDO SERIAL PRIMARY KEY,
	ID_FILIAL INTEGER NOT NULL,
	CONSTRAINT FK1_FILIAL
        FOREIGN KEY(ID_FILIAL) 
        REFERENCES TB_FILIAL(ID_FILIAL),	
	ID_PESSOA INTEGER NOT NULL,
	CONSTRAINT FK1_PESSOA
        FOREIGN KEY(ID_PESSOA) 
        REFERENCES TB_PESSOA(ID_PESSOA),	
	DEC_VALOR_TOTAL DECIMAL(8, 2) NOT NULL,
	DEC_VALOR_ENTREGA DECIMAL(8, 2) NOT NULL,
	INT_QTD_ITENS INTEGER NOT NULL,
	DT_PEDIDO TIMESTAMP NOT NULL,
	ID_STATUS_PEDIDO INTEGER NOT NULL,
	ID_FORMA_PAGAMENTO INTEGER NOT NULL,
	STR_OBSERVAÇÃO VARCHAR(100) NOT NULL
);

CREATE TABLE TB_PEDIDO_ITEM(
	ID_PEDIDO_ITEM SERIAL PRIMARY KEY,
	ID_PEDIDO INTEGER NOT NULL,
	CONSTRAINT FK1_PEDIDO
        FOREIGN KEY(ID_PEDIDO) 
        REFERENCES TB_PEDIDO(ID_PEDIDO),		
	ID_PRODUTO INTEGER NOT NULL,
	CONSTRAINT FK1_PRODUTO
        FOREIGN KEY(ID_PRODUTO) 
        REFERENCES TB_PRODUTO(ID_PRODUTO),	
	INT_QUANTIDADE INTEGER NOT NULL
);

CREATE TABLE TB_CARTAO_CREDITO(
	ID_CARTAO_CREDITO SERIAL PRIMARY KEY,
	ID_PESSOA INTEGER NOT NULL,
	CONSTRAINT FK1_PESSOA
        FOREIGN KEY(ID_PESSOA) 
        REFERENCES TB_PESSOA(ID_PESSOA),	
	ID_FORMA_PAGAMENTO INTEGER NOT NULL,
	STR_NOME_NO_CARTAO VARCHAR(100) NOT NULL,
	STR_NUMERO_CARTAO VARCHAR(500) NOT NULL,
	STR_VENCIMENTO_CARTAO VARCHAR(5) NOT NULL,
	STR_CVV VARCHAR(200) NOT NULL
);

CREATE TABLE TB_PEDIDO_CARTAO_CREDITO(
	ID_CARTAO_CREDITO INTEGER NOT NULL,
	ID_PEDIDO INTEGER NOT NULL,
	CONSTRAINT FK1_PEDIDO
        FOREIGN KEY(ID_PEDIDO) 
        REFERENCES TB_PEDIDO(ID_PEDIDO),	
	ID_STATUS_PAGAMENTO INTEGER NOT NULL
);

CREATE TABLE TB_PEDIDO_PIX(
	ID_PEDIDO INTEGER NOT NULL,
	CONSTRAINT FK1_PEDIDO
        FOREIGN KEY(ID_PEDIDO) 
        REFERENCES TB_PEDIDO(ID_PEDIDO),	
	STR_CODIGO_PIX VARCHAR(500) NOT NULL,
	ID_STATUS_PAGAMENTO INTEGER NOT NULL
);

CREATE TABLE TB_FILA_PEDIDO(
	ID_FILA_PEDIDO SERIAL PRIMARY KEY,
	ID_FILIAL INTEGER NOT NULL,
	CONSTRAINT FK1_FILIAL
        FOREIGN KEY(ID_FILIAL) 
        REFERENCES TB_FILIAL(ID_FILIAL),	
	ID_PEDIDO INTEGER NOT NULL,
	CONSTRAINT FK1_PEDIDO
        FOREIGN KEY(ID_PEDIDO) 
        REFERENCES TB_PEDIDO(ID_PEDIDO)	
);

--ID_SEXO
INSERT INTO TB_DOMINIO(STR_CHAVE, STR_DESCRICAO, ID_DOMINIO)
VALUES('ID_SEXO', 'Masculino', 1), ('ID_SEXO', 'Feminino', 2), ('ID_SEXO', 'Outros', 3);

--ID_PESSOA_TIPO
INSERT INTO TB_DOMINIO(STR_CHAVE, STR_DESCRICAO, ID_DOMINIO)
VALUES('ID_PESSOA_TIPO', 'Cliente', 1);

--ID_TIPO_DOCUMENTO
INSERT INTO TB_DOMINIO(STR_CHAVE, STR_DESCRICAO, ID_DOMINIO)
VALUES('ID_TIPO_DOCUMENTO', 'CPF', 1), ('ID_TIPO_DOCUMENTO', 'CNPJ', 2);

--ID_STATUS_PEDIDO
INSERT INTO TB_DOMINIO(STR_CHAVE, STR_DESCRICAO, ID_DOMINIO)
VALUES('ID_STATUS_PEDIDO', 'Finalizado', 1), ('ID_STATUS_PEDIDO', 'Cancelado', 2),
('ID_STATUS_PEDIDO', 'Em Andamento', 3), ('ID_STATUS_PEDIDO', 'Em Entrega', 4);

--ID_FORMA_PAGAMENTO
INSERT INTO TB_DOMINIO(STR_CHAVE, STR_DESCRICAO, ID_DOMINIO)
VALUES('ID_FORMA_PAGAMENTO', 'PIX', 1), ('ID_FORMA_PAGAMENTO', 'Crédito', 2),
('ID_FORMA_PAGAMENTO', 'Débito', 3), ('ID_FORMA_PAGAMENTO', 'Dinheiro', 4);

--ID_STATUS_PAGAMENTO
INSERT INTO TB_DOMINIO(STR_CHAVE, STR_DESCRICAO, ID_DOMINIO)
VALUES('ID_STATUS_PAGAMENTO', 'Aprovado', 1), ('ID_STATUS_PAGAMENTO', 'Falha', 2),
('ID_STATUS_PAGAMENTO', 'Reembolsado', 3);