services:
  db:
    image: postgres:12.19
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=MinhaLanchonete
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:3000
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5058:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=MinhaLanchonete;Username=postgres;Password=postgres;
    networks:
      - app-network

volumes:
  pgdata:
networks:
  app-network: