services:
  db:
    image: postgres:12.19
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=MinhaLanchonete
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:5058"
      - "9001:7292"

volumes:
  pgdata: