services:
  db:
    image: postgres:12.19
    restart: always   
    shm_size: 128mb 
    env_file:
        - .env
    volumes:
      - pgdata:/var/lib/postgresql/data 
  app:
    depends_on:
        - db
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"

volumes:
  pgdata: